### ISSUE TITLE
DeepBBT : the outputs of modified Roberta don't have hidden states

### ISSUE THREAD

**Issue by Desein-Yang** [txsun1997/Black-Box-Tuning#14]
Hello, there is a bug in RobertaL Model ouput  when I run deepbbt because it do not have hidden state even the config.output_hidden_states = True (Line439).

Then I found the Line 975 of deep_modeling_roberta.py only output a dict with logit rather than the original MskedLMOutput, which leads to the above bug.  

When I try to directly replace the logit of MaskedLMOutput to fix it, it suggest the inner model also do not output hidden state. I would appreciate if you could help to fix that !

**Comment by txsun1997** [comment]
Thanks for your issue! I've updated the `deep_modeling_roberta.py`, please try again :)

**Comment by Desein-Yang** [comment]
Thank you very much :)  It works well for me.
