### ISSUE TITLE
Can the user-side can obtain the final prompt in literal?

### ISSUE THREAD

**Issue by LemonQC** [txsun1997/Black-Box-Tuning#15]
I found this optimization is about vector after user obtain the results from server. I wander if there any possible to get the final prompt text to help other people to design prompts

**Comment by txsun1997** [comment]
No, our prompt is continuous and it may hurt performance if rounding it into a discrete prompt. I'd like to recommend some related works that optimize discrete prompts: [https://github.com/txsun1997/LMaaS-Papers#black-box-optimization](https://github.com/txsun1997/LMaaS-Papers#black-box-optimization)
