### ISSUE TITLE
关于Dbpedia

### ISSUE THREAD

**Issue by hccngu** [txsun1997/Black-Box-Tuning#17]
/remote-home/txsun/zfhe/dbpedia_csv.tar.gz 这个文件可以提供下吗？使用datasets自动下载dbpedia出问题了：
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Read timed out. (read timeout=100.0)
谢谢哈～

**Comment by txsun1997** [comment]
hi @hccngu 

The DBPedia data is in `./data/` now. See also the change of the `URL` in the `./data/dbpedia.py`

**Comment by hccngu** [comment]
Thanks~
