### ISSUE TITLE
结果复现问题

### ISSUE THREAD

**Issue by hccngu** [txsun1997/Black-Box-Tuning#18]
您好，我在sst2，yelpp和agnews上的(seed=42)复现结果为87.61(90.33)，91.00(92.86)，82.53(85.28)。
括号中是论文报告的结果，我所使用的机器是V100，配置如下：
python -u bbt.py \
  --task_name XXX \
  --n_prompt_tokens 50 \
  --intrinsic_dim 500 \
  --k_shot 16 \
  --device "cuda:3" \
  --seed 42 \
  --loss_type "ce" \
  --cat_or_add "add" \
  --budget 8000 \
  --print_every 50 \
  --eval_every 100
请问是我的参数设置有问题吗？或者其他什么原因导致的结果上的差异吗？

**Comment by txsun1997** [comment]
@hccngu 您好：

SST2, YelpP, AGNews上90.33, 92.86, 85.28是BBTv2的结果，请按照[https://github.com/txsun1997/Black-Box-Tuning#using-bbtv2](https://github.com/txsun1997/Black-Box-Tuning#using-bbtv2)运行`deepbbt.py`. 具体种子的结果可以参考[Google Sheets](https://docs.google.com/spreadsheets/d/1FA9zMW613OoskI_fBXuZNNBVo7RFV5OvdZ0YHnA2j5Q/edit?usp=sharing)，请根据里面的结果设置各个任务上的`--sigma`和`--alpha`. 如有较大出入，欢迎再来反馈:)

**Comment by hccngu** [comment]
OK, Thanks~
