### ISSUE TITLE
Why not calculate prompt on the server side?

### ISSUE THREAD

**Issue by hdzhang-code** [txsun1997/Black-Box-Tuning#5]
In the paper, it is assumed that the user can access only an inference API provided by the server, and thus we need a solution to calculate the prompt on the user side. This limit is from the requirement of keeping PLM parameters secret.

Why not calculate the prompt on the server side. Returning the prompt, or, the gradient on the prompt, does not leak PLM parameters, too. 

We do not prefer the above solution, because of additional burden at the server side?

**Comment by txsun1997** [comment]
Yeah, it is okay to perform SGD to obtain an optimized prompt for the user. But the optimization can be expensive for large models. The computation and memory cost of SGD/Adam is proportional to the size of the model. If we consider hyper-parameter tuning (in fact, this is necessary for prompt tuning), the cost is more expensive. In comparison, black-box tuning only requires the model forward process, which is cheaper and easier to be accelerated with the support of ONNX/TensorRT.

For another solution, if the server returns the gradient w.r.t. the prompt to the user, the deployed model will be vulnerable (See [LAMP: Extracting Text from Gradients with Language Model Priors](https://arxiv.org/pdf/2202.08827.pdf)).

So the answer is yes, the solution you mentioned will translate to additional burden of the server.
