### ISSUE TITLE
Truncation Length

### ISSUE THREAD

**Issue by MM-IR** [txsun1997/Black-Box-Tuning#6]
Hi, very nice work. Also, we are currently trying to reproduce your work as our baseline.

Can I ask you what strategies do you try with in our Yelp P. dataset? Especially for very long sentences. In my current experiments, it tells me that I have to perform truncation...

Thanks!

**Comment by txsun1997** [comment]
Hi, in our implementation we simply filter out samples that contain more than 512 tokens. See https://github.com/txsun1997/Black-Box-Tuning/blob/b759fc2b7579907ccba420880a8df80d66754381/dataloader.py#L109-L116

Though our used datasets are not exactly the same as the original ones, we adopt a few-shot setting and all of the models are evaluated on the same generated datasets, so it is still a fair comparison.

**Comment by MM-IR** [comment]
Thanks for your help! Nice work!
